<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>MobileTweaks</AssemblyName>
    <RootNamespace>Celeste.Mod.MobileTweaks</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Celeste">
      <HintPath>D:\SteamLibrary\steamapps\common\Celeste\Celeste.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FNA">
      <HintPath>D:\SteamLibrary\steamapps\common\Celeste\FNA.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>D:\SteamLibrary\steamapps\common\Celeste\MonoMod.RuntimeDetour.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MMHOOK_Celeste">
      <HintPath>D:\SteamLibrary\steamapps\common\Celeste\MMHOOK_Celeste.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
